### ISSUE TITLE
demo里的apk貌似检测不到

### ISSUE THREAD

**Issue by Chopin68** [DDGRCF/YOLOX_OBB_Application#1]
![微信图片_20221102203012](https://user-images.githubusercontent.com/75252160/199490033-1605b793-88e3-4476-b2f9-4c726c0dc54f.jpg)
很奇怪的结果，是因为我放的图是原图吗 是dota1.5里的测试图片

**Comment by DDGRCF** [comment]
抱歉，程序中有个bug，现在修复了

**Comment by Chopin68** [comment]
> 抱歉，程序中有个bug，现在修复了

成功了，效果很不错
![微信图片_20221104232527](https://user-images.githubusercontent.com/75252160/200013351-fe687efd-f5b7-43b4-964e-800fbdcd08f1.jpg)
